version: '3.8'
services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile

    container_name: backend
    ports:
      - "8080:8080"
    env_file:
      - ./.env
    depends_on:
      - mongodb

  
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile

    container_name: frontend
    ports:
      - "80:80"
    depends_on:
      - backend
  
  mongodb:
    image: mongo:latest
    container_name: mongodb_server
    env_file: ./.env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGODB_USER
      - MONGO_INITDB_ROOT_PASSWORD=$MONGODB_PASSWORD
    ports:
      - "27017:27017"
    volumes:
      - ./../mydata:/data/db

# Volumes define
volumes: 
  mydata:

